# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless-go-lambda-dynamo

# app and org for use with dashboard.serverless.com
#app: 
#org: 

frameworkVersion: "3"
#useDotenv: true

provider:
  name: aws
  runtime: go1.x
  #lambdaHashingVersion: 20201221
  #environment:
  #  APP_ID: ${param:APP_ID}
  #  PRIVATE_KEY: ${param:PRIVATE_KEY}
  #  WEBHOOK_SECRET: ${param:WEBHOOK_SECRET}
  #  NODE_ENV: production
  #  LOG_LEVEL: debug

package: 
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - httpApi:
          path: /hello
          method: get
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get